manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: minhe7735
      url-base: https://github.com/minhe7735
    - name: inorichi
      url-base: https://github.com/inorichi
  projects:
    - name: zmk
      remote: minhe7735
      revision: urob_main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: inorichi
      revision: main
  self:
    path: config