manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: minhe7735
      url-base: https://github.com/minhe7735
  projects:
    - name: zmk
      remote: minhe7735
      revision: testbranch
      import: app/west.yml
  self:
    path: config