manifest:
  remotes:
    - name: urob
      url-base: https://github.com/urob
    - name: inorichi
      url-base: https://github.com/inorichi
  projects:
    - name: zmk
      remote: urob
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: inorichi
      revision: main
  self:
    path: config