manifest:
  remotes:
    - name: minhe7735
      url-base: https://github.com/minhe7735
  projects:
    - name: zmk
      remote: minhe7735
      revision: urob
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: minhe7735
      revision: main
  self:
    path: config