on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: urob/zmk/.github/workflows/build-user-config.yml@build-with-submodules
    uses: petejohanson/zmk/.github/workflows/build-user-config.yml@core/zephyr-3.5-update

